all_pairs_stored <- c("1INCHUSD",  "AAVEUSD",   "ACAUSD",    "ACHUSD",    "ADAUSD"  ,  "ADXUSD"   , "AGLDUSD"  ,
               "AIRUSD",    "AKTUSD" ,   "ALCXUSD",   "ALGOUSD",   "ALICEUSD"  ,"ALPHAUSD" , "ANKRUSD"  ,
               "ANTUSD" ,   "APEUSD" ,   "API3USD",   "APTUSD",    "ARBUSD"    ,"ARPAUSD"  , "ASTRUSD"  ,
               "ATLASUSD",  "ATOMUSD",   "AUDIOUSD",  "AUDUSD",    "AVAXUSD"  , "AXSUSD"   , "BADGERUSD",
               "BALUSD"   , "BANDUSD",   "BATUSD",    "BCHUSD",    "BICOUSD" ,  "BITUSD"   , "BLURUSD"  ,
               "BLZUSD"  ,  "BNCUSD" ,   "BNTUSD",    "BOBAUSD",   "BONDUSD"  , "BONKUSD"  , "BRICKUSD" ,
               "BSXUSD"  ,  "BTTUSD" ,   "C98USD",    "CELRUSD",   "CFGUSD"  ,  "CHRUSD"   , "CHZUSD"   ,
               "COMPUSD" ,  "COTIUSD",   "CQTUSD",    "CRVUSD" ,   "CSMUSD"  ,  "CTSIUSD"  , "CVCUSD"   ,
               "CVXUSD"  ,  "DAIUSD",    "DASHUSD",   "DENTUSD",   "DOTUSD"   , "DYDXUSD"  , "DYMUSD"   ,
               "EGLDUSD"  , "ENJUSD" ,   "ENSUSD",    "EOSUSD" ,   "ETHPYUSD",  "ETHWUSD" ,  "EULUSD"   ,
               "EURTUSD" ,  "EWTUSD"  ,  "FARMUSD",   "FETUSD" ,   "FIDAUSD"  , "FILUSD" ,   "FISUSD"   ,
               "FLOWUSD" ,  "FLRUSD" ,   "FORTHUSD",  "FTMUSD" ,   "FXSUSD"  ,  "GALAUSD" ,  "GALUSD"   ,
               "GARIUSD" ,  "GHSTUSD" ,  "GLMRUSD",  "GMTUSD"  ,  "GMXUSD"    ,"GNOUSD"  ,  "GRTUSD"   ,
               "GSTUSD"  ,  "GTCUSD" ,   "HDXUSD",    "HFTUSD" ,   "ICPUSD"    ,"ICXUSD"  ,  "IDEXUSD"  ,
               "IMXUSD"  ,  "INJUSD" ,   "INTRUSD",   "JASMYUSD",  "JTOUSD"    ,"JUNOUSD" ,  "JUPUSD"   ,
               "KARUSD"  ,  "KAVAUSD" ,  "KEEPUSD",   "KEYUSD" ,   "KILTUSD"   ,"KINTUSD" ,  "KINUSD"   ,
               "KNCUSD"  ,  "KP3RUSD",   "KSMUSD",    "LCXUSD"  ,  "LDOUSD"    ,"LINKUSD"  , "LMWRUSD"  ,
               "LPTUSD"  ,  "LRCUSD" ,   "LSKUSD",    "LUNA2USD",  "LUNAUSD"   ,"MANAUSD",   "MASKUSD"  ,
               "MATICUSD" , "MCUSD"  ,   "MINAUSD",   "MIRUSD",    "MKRUSD"    ,"MNGOUSD" ,  "MOONUSD"  ,
               "MOVRUSD" ,  "MSOLUSD",   "MULTIUSD",  "MVUSD",     "MXCUSD"    ,"NANOUSD"  , "NEARUSD"  ,
               "NMRUSD"  ,  "NODLUSD",   "NYMUSD",    "OCEANUSD",  "OGNUSD"    ,"OMGUSD"   , "OPUSD"    ,
               "ORCAUSD" ,  "OXTUSD" ,   "OXYUSD",    "PAXGUSD",   "PEPEUSD"   ,"PERPUSD"  , "PHAUSD"   ,
               "PLAUSD"  ,  "POLISUSD",  "POLSUSD",   "POLUSD",    "PONDUSD"   ,"POWRUSD"  , "PSTAKEUSD",
               "PYTHUSD" ,  "PYUSDUSD",  "QNTUSD",    "QTUMUSD",   "RADUSD"    ,"RAREUSD"  , "RARIUSD"  ,
               "RAYUSD"  ,  "RBCUSD",    "RENUSD",    "REPV2USD",  "REQUSD"    ,"RLCUSD"   , "RNDRUSD"  ,
               "ROOKUSD" ,  "RPLUSD",    "RUNEUSD",   "SAMOUSD",   "SANDUSD"   ,"SBRUSD"   , "SCRTUSD"  ,
               "SCUSD"   ,  "SDNUSD",    "SEIUSD",    "SGBUSD" ,   "SHIBUSD"   ,"SNXUSD"   , "SOLUSD"   ,
               "SPELLUSD",  "SRMUSD",    "STEPUSD",   "STGUSD" ,   "STORJUSD"  ,"STXUSD"   , "SUIUSD"   ,
               "SUPERUSD" , "SUSHIUSD",  "SYNUSD",    "TBTCUSD",   "TEERUSD"   ,"TIAUSD"   , "TLMUSD"   ,
               "TOKEUSD"  , "TRUUSD",    "TRXUSD",    "TUSD"   ,   "TUSDUSD"   ,"TVKUSD"   , "UMAUSD"   ,
               "UNFIUSD" ,  "UNIUSD",    "USDCUSD",   "USDTZUSD",  "USTUSD"   , "WAVESUSD" , "WAXLUSD"  ,
               "WBTCUSD" ,  "WIFUSD",    "WOOUSD",    "XBTPYUSD" , "XCNUSD"  ,  "XDGUSD"   , "XETCZUSD" ,
               "XETHZUSD",  "XLTCZUSD",  "XMLNZUSD",  "XREPZUSD" , "XRTUSD" ,   "XTZUSD"   , "XXBTZUSD" ,
               "XXLMZUSD" , "XXMRZUSD",  "XXRPZUSD",  "XZECZUSD" , "YFIUSD",    "YGGUSD"   , "ZEURZUSD" ,
               "ZGBPZUSD",  "ZRXUSD", "AEVOUSD", "ALTUSD", "ARKMUSD", "AUCTIONUSD", "BEAMUSD", "BIGTIMEUSD",
               "BODENUSD", "CLOUDUSD",  "CPOOLUSD", "DRIFTUSD", "ENAUSD", "FLOKIUSD", "GFIUSD", "HNTUSD", "HONEYUSD", "KMNOUSD",
               "KUJIUSD", "L3USD", "LITUSD", "MOGUSD", "MPLUSD", "NOSUSD", "ONDOUSD", "OSMOUSD", "RENDERUSD",
               "PENDLEUSD", "POPCATUSD", "PRIMEUSD", "REZUSD", "STRDUSD", "STRKUSD", "TAOUSD", "TRACUSD", "TREMPUSD",
               "SAGAUSD", "TURBOUSD", "WUSD", "ZEUSUSD", "ZEXUSD", "ZROUSD")
  